[build]
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SITE_KEY"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis", "gaxios", "google-auth-library", "@neondatabase/serverless", "razorpay", "resend"]

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888

[[redirects]]
  from = "/ingest/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ingest/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200