[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis", "gaxios", "google-auth-library"]

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888